### ISSUE TITLE
Add support for links in the frontend.

### ISSUE THREAD

**Issue by Zartaj0** [cdump/evmole#2]
If it's possible to add support for etherscan links in [this](https://cdump.github.io/evmole/) frontend, that would be great. 

We won't need to copy the bytecode but just the link, and the backend will fetch the bytecode from etherscan.

**Comment by cdump** [comment]
@Zartaj0 try upgraded version: https://cdump.github.io/evmole/#0xdac17f958d2ee523a2206206994597c13d831ec7/eth (reload page with Ctrl+F5)

**Comment by Zartaj0** [comment]
Amazing, thanks :)
