### ISSUE TITLE
Generates incorrect args for `transfer` in Deez Nuts contract

### ISSUE THREAD

**Issue by shouc** [cdump/evmole#3]
Running evmole on this contract https://etherscan.io/address/0xb57E874082417b66877429481473CF9FCd8e0b8a#code

<img width="474" alt="Screenshot 2024-02-22 at 6 30 54 PM" src="https://github.com/cdump/evmole/assets/10573715/ab691fff-8d6a-4501-9100-78dc4a205328">

I have also tried Dedaub and Hemdall, which both can produce correct result.

**Comment by cdump** [comment]
Hi, thanks for report.
I'll try to fix it someday after implementing some ideas in the code.

Note to me in the future: vm SLOAD+CALLER

**Comment by cdump** [comment]
Fixed: https://cdump.github.io/evmole/#0xb57E874082417b66877429481473CF9FCd8e0b8a/eth
