### ISSUE TITLE
Can add detect function support payable ?

### ISSUE THREAD

**Issue by CaiJiJi** [cdump/evmole#6]
thanks

**Comment by cdump** [comment]
It's trivial (at least for Solidity). I'll add this to the backlog and implement it later.

**Comment by wtdcode** [comment]
> It's trivial (at least for Solidity). I'll add this to the backlog and implement it later.

Maybe we can consider prioritizing this? This helps generate a somehow "full" abi.

**Comment by cdump** [comment]
> prioritizing this

After https://github.com/cdump/evmole/issues/9, it will be easier to implement new features only in 1 language.
I'm on 4'th step of [TODO list](https://github.com/cdump/evmole/issues/9#issuecomment-2294823719)

**Comment by wtdcode** [comment]
I can help implement this so that evmole can return a full `Function`

**Comment by cdump** [comment]
Do you want to return https://docs.rs/alloy-json-abi/0.8.0/alloy_json_abi/struct.Function.html ? If yes, what about `outputs` field, which is not `Optional`, we don't have this information. Using empty Vec there may mislead the users.

**Comment by wtdcode** [comment]
Oh, you are correct. My own code always ignores this field so I forget this. Maybe another standalone function to return if a selector is `payable` or not.

**Comment by cdump** [comment]
I've conducted some experiments in the [state_mutability branch](https://github.com/cdump/evmole/tree/state_mutability), the main idea is [described here](https://github.com/cdump/evmole/commit/36eff45823f4590ae6dec314807e6865e89efc03#diff-00657c10745f74bedef2b4c37540af1735fb9989cf37c77ec82ef18c2bc78dffR93)

Using the `largest1k` dataset, I couldn't achieve more than a 53% success rate (counting `view` & `pure` from etherscan as `payable`), which is far from satisfactory.

We need to explore alternative approaches.

P.S. In modern Vyper, we can extract this information from metadata, but let's focus on solving the Solidity issue first.

**Comment by cdump** [comment]
I've added normal benchmark to 'state_mutability' branch, current results:

'simple' always returns 'nonpayable'

**strict cmp ('view' != 'nonpayable'):**
```
dataset largest1k (1000 contracts, 24427 functions), evmole-rs:
  bad:  20846 functions 85.34%

dataset largest1k (1000 contracts, 24427 functions), heimdall-rs:
  bad:  13403 functions 54.87%

dataset largest1k (1000 contracts, 24427 functions), sevm:
  bad:  14417 functions 59.02%

dataset largest1k (1000 contracts, 24427 functions), simple:
  bad:  14864 functions 60.85%
```

**non-strict cmp ('view' and 'pure' == 'nonpayable')** - https://github.com/cdump/evmole/commit/fda622a5e63ad2fb5f207f52ce246a90abd3e0a2#diff-11f0a34f6da0d500562ceadaae6abfb4f9c2dd2ae5ff01ffd0e879e35ab70bdeR242
```
dataset largest1k (1000 contracts, 24427 functions), evmole-rs:
  bad:  16177 functions 66.23%

dataset largest1k (1000 contracts, 24427 functions), heimdall-rs:
  bad:  6201 functions 25.39%

dataset largest1k (1000 contracts, 24427 functions), sevm:
  bad:  501 functions 2.05%

dataset largest1k (1000 contracts, 24427 functions), simple:
  bad:  643 functions 2.63%
```


```
$ cd benchmarks/
$ DATASETS=largest1k PROVIDERS_MUTABILITY="evmole-rs sevm heimdall-rs" make benchmark-mutability
$ python3 ./compare.py --datasets largest1k --mode mutability
```

**Comment by wtdcode** [comment]
My two cents: to increase precision, we should firstly decode abi and ensure the call data conforms with abi?

Why the precision is just 60%? Your algorithm seems good and reasonable.
________________________________

**Comment by cdump** [comment]
I found a bug - we need to track reverts even inside 'skip_until_inside_function', because if all functions are not payable, then Solidity checks CALLVALUE at the beginning of the contract execution.
After the fix, we got:
`bad: 59 functions 0.24%` in non-strict mode and `bad: 14,278 functions 58.45%` in strict mode.
Now we need to improve strict mode.

**Comment by wtdcode** [comment]
Yes, that’s my point. Solc will implicitly generate checks against call data (and also return data).
________________________________

**Comment by cdump** [comment]
Bug was about location of this check - at the begging of the whole contract or after checking for function selector - inside function body

**Comment by wtdcode** [comment]
Yes, I misunderstood.
________________________________

**Comment by cdump** [comment]
Merged to the master, will make release soon
